# Generated by Django 4.0.6 on 2022-11-14 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_producttype_dl_purchase_producttype_dl_sales'),
        ('warehouse', '0003_alter_stock_summary_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalletTransferEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgodown', models.CharField(max_length=30)),
                ('tgodown', models.CharField(max_length=30)),
                ('qty', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('created', models.DateField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product_master')),
            ],
        ),
    ]
