# Generated by Django 4.0.6 on 2022-11-14 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_pinv_series'),
        ('warehouse', '0004_pallettransferentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallettransferentry',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pallet', to='company.company'),
            preserve_default=False,
        ),
    ]
