# Generated by Django 4.0.6 on 2022-11-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_pallettransferentry_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_summary',
            name='closing_balance',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
