# Generated by Django 4.0.6 on 2022-11-22 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_pinv_series'),
        ('warehouse', '0006_alter_stock_summary_closing_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortagedamageentry',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortagedamageentry',
            name='createdby',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
