# Generated by Django 4.0.5 on 2022-08-26 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('inventory', '0001_initial'),
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('no', models.CharField(max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('no', models.CharField(max_length=50, verbose_name='Jobwork No')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=15)),
                ('start', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company', verbose_name='Company')),
                ('joborder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobwork', to='planning.joborder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobwork', to='inventory.product_master')),
            ],
        ),
        migrations.CreateModel(
            name='RMIndent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('no', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Godown'), ('3', 'Production')], max_length=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company', verbose_name='Company')),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rmindent', to='production.jobcard', verbose_name='JobCard')),
            ],
        ),
        migrations.CreateModel(
            name='RMIndentItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=15)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planning.bom')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product_master')),
                ('rmindent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.rmindent', verbose_name='Indent')),
            ],
        ),
        migrations.CreateModel(
            name='RMItemGodown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mrp', models.CharField(max_length=51)),
                ('batch', models.CharField(max_length=51)),
                ('godown', models.CharField(max_length=51)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rmitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.rmindentitems')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumptionItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mrp', models.CharField(max_length=51)),
                ('batch', models.CharField(max_length=51)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=15)),
                ('consumption', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumption', to='production.consumption')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumption_item', to='inventory.product_master')),
            ],
        ),
        migrations.AddField(
            model_name='consumption',
            name='jobcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumption', to='production.jobcard', verbose_name='JobCard'),
        ),
        migrations.CreateModel(
            name='ConsumableIndent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('no', models.CharField(max_length=10)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company', verbose_name='Company')),
                ('drawn_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumable_indent_drawn_by', to=settings.AUTH_USER_MODEL, verbose_name='Drawn_by')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumable_indent_issued_by', to=settings.AUTH_USER_MODEL, verbose_name='Issuer')),
            ],
        ),
        migrations.CreateModel(
            name='ConsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=15)),
                ('con_qty', models.DecimalField(decimal_places=4, max_digits=15)),
                ('indent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumable_indent_items', to='production.consumableindent')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumableitem', to='inventory.product_master')),
            ],
        ),
    ]
