# Generated by Django 4.0.6 on 2022-08-30 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumableindent',
            options={'ordering': ['-no']},
        ),
        migrations.AlterModelOptions(
            name='consumption',
            options={'ordering': ['-no']},
        ),
        migrations.AlterModelOptions(
            name='consumptionitems',
            options={'ordering': ['-consumption']},
        ),
        migrations.AlterModelOptions(
            name='jobcard',
            options={'ordering': ['-no']},
        ),
        migrations.AlterModelOptions(
            name='rmindent',
            options={'ordering': ['-no']},
        ),
        migrations.AlterModelOptions(
            name='rmindentitems',
            options={'ordering': ['-rmindent']},
        ),
    ]
