# Generated by Django 4.0.6 on 2022-09-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_consumableindent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='start',
            field=models.DateField(),
        ),
    ]
