# Generated by Django 4.0.6 on 2022-09-05 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_jobcard_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptionitems',
            name='consumption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption', to='production.consumption'),
        ),
    ]
