# Generated by Django 4.0.6 on 2022-09-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_consumptionitems_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='rqty',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
