# Generated by Django 4.0.6 on 2022-09-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_jobcard_rqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='qty',
            field=models.DecimalField(decimal_places=4, default=300, max_digits=15),
            preserve_default=False,
        ),
    ]
