# Generated by Django 4.0.6 on 2022-10-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_rmitemgodown_created_rmitemgodown_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'RM Indent'), ('3', 'Material Transfer'), ('4', 'Closed')], default=1, max_length=1),
        ),
    ]
