# Generated by Django 4.0.6 on 2022-08-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_purchase_order_currency_purchase_order_ex_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitnote',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar')], default='INR', max_length=20),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='ex_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
        ),
        migrations.AddField(
            model_name='grn',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar')], default='INR', max_length=20),
        ),
        migrations.AddField(
            model_name='grn',
            name='ex_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
        ),
        migrations.AddField(
            model_name='purchase',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar')], default='INR', max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='ex_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='ex_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
        ),
    ]
