# Generated by Django 4.0.6 on 2022-09-03 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_debitnote_currency_debitnote_ex_rate_grn_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grnitems',
            name='grn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.grn'),
        ),
        migrations.AlterField(
            model_name='poitems',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchase_order'),
        ),
    ]
