# Generated by Django 4.0.6 on 2022-09-03 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_alter_grnitems_grn_alter_poitems_po'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitnoteitems',
            name='debitNote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.debitnote'),
        ),
        migrations.AlterField(
            model_name='purchasereturnitems',
            name='pr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchasereturn'),
        ),
        migrations.AlterField(
            model_name='qdnitems',
            name='qdn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.qdn'),
        ),
    ]
