# Generated by Django 4.0.6 on 2022-09-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_alter_debitnoteitems_debitnote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitnote',
            name='seller_gstin',
            field=models.CharField(blank=True, max_length=151, null=True),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='shipto_gstin',
            field=models.CharField(blank=True, max_length=151, null=True),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='seller_gstin',
            field=models.CharField(blank=True, max_length=151, null=True),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='shipto_gstin',
            field=models.CharField(blank=True, max_length=151, null=True),
        ),
        migrations.AlterField(
            model_name='qdn',
            name='seller_gstin',
            field=models.CharField(blank=True, max_length=151, null=True),
        ),
        migrations.AlterField(
            model_name='qdn',
            name='shipto_gstin',
            field=models.CharField(blank=True, max_length=151, null=True),
        ),
    ]
