# Generated by Django 4.0.6 on 2022-10-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_alter_debitnote_seller_gstin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitnote',
            name='currency',
            field=models.CharField(default='INR', max_length=20),
        ),
        migrations.AlterField(
            model_name='grn',
            name='currency',
            field=models.CharField(default='INR', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='currency',
            field=models.CharField(default='INR', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='currency',
            field=models.CharField(default='INR', max_length=20),
        ),
    ]
