# Generated by Django 4.0.6 on 2022-11-23 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_alter_debitnote_currency_alter_grn_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piitems',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
