# Generated by Django 4.0.5 on 2023-01-03 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_pinv_series'),
        ('purchase', '0008_piitems_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grn',
            options={'ordering': ['grn_no']},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['pi_no']},
        ),
        migrations.AlterModelOptions(
            name='purchase_order',
            options={'ordering': ['po_no']},
        ),
        migrations.AlterUniqueTogether(
            name='grn',
            unique_together={('company', 'grn_no')},
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('company', 'pi_no')},
        ),
        migrations.AlterUniqueTogether(
            name='purchase_order',
            unique_together={('company', 'po_no')},
        ),
    ]
