# Generated by Django 4.0.5 on 2023-01-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_alter_grn_options_alter_purchase_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='po_no',
            field=models.CharField(max_length=151),
        ),
    ]
