# Generated by Django 4.0.5 on 2023-02-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_alter_purchase_order_po_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poitems',
            name='pack',
            field=models.CharField(default=0, max_length=151),
        ),
    ]
