# Generated by Django 4.0.5 on 2022-08-26 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('inventory', '0001_initial'),
        ('ledgers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=51)),
                ('description', models.TextField()),
                ('last_date', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product_master')),
            ],
        ),
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('no', models.CharField(max_length=50, verbose_name='Job Order No')),
                ('name', models.CharField(max_length=50, verbose_name='Job Name')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=25)),
                ('remain_qty', models.DecimalField(decimal_places=4, max_digits=25)),
                ('date', models.DateField(verbose_name='Job Card Date')),
                ('due_date', models.DateTimeField()),
                ('ref', models.CharField(max_length=50, verbose_name='Reference')),
                ('details', models.CharField(max_length=50, verbose_name='Details')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('issuedby', models.CharField(max_length=51, verbose_name='Issued By')),
                ('remarks', models.TextField()),
                ('status', models.BooleanField()),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobcard', to='planning.bom')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobcard', to='inventory.product_master')),
            ],
        ),
        migrations.CreateModel(
            name='BomItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=24)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planning.bom')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product_master')),
            ],
        ),
        migrations.CreateModel(
            name='SalesProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('p_qty', models.DecimalField(decimal_places=4, max_digits=15)),
                ('a_qty', models.DecimalField(decimal_places=4, max_digits=15)),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledgers.division', verbose_name='Division')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product_master', verbose_name='Product')),
            ],
            options={
                'unique_together': {('product', 'division', 'from_date', 'to_date')},
            },
        ),
    ]
