# Generated by Django 4.0.6 on 2022-08-30 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bom',
            options={'ordering': ['product']},
        ),
        migrations.AlterModelOptions(
            name='bomitems',
            options={'ordering': ['bom']},
        ),
        migrations.AlterModelOptions(
            name='joborder',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='salesprojection',
            options={'ordering': ['product']},
        ),
    ]
