# Generated by Django 4.0.6 on 2022-09-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_alter_bom_options_alter_bomitems_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='name',
            field=models.CharField(max_length=151),
        ),
    ]
