# Generated by Django 4.0.6 on 2022-09-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_alter_bom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='due_date',
            field=models.DateField(),
        ),
    ]
