# Generated by Django 4.0.6 on 2022-09-15 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_alter_joborder_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bom',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
