# Generated by Django 4.0.6 on 2022-10-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_bom_created_bom_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'In Progress'), ('3', 'Completed')], default=1, max_length=1),
        ),
    ]
