# Generated by Django 4.0.5 on 2022-08-26 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('ledgers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_master',
            name='dl_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_ledger', to='ledgers.ledgerstype'),
        ),
        migrations.AddField(
            model_name='product_master',
            name='dl_sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_ledger', to='ledgers.ledgerstype'),
        ),
        migrations.AddField(
            model_name='product_master',
            name='product_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventory.class'),
        ),
        migrations.AddField(
            model_name='product_master',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.producttype'),
        ),
        migrations.AddField(
            model_name='product_master',
            name='sub_brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventory.subbrand'),
        ),
        migrations.AddField(
            model_name='product_master',
            name='sub_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventory.subclass'),
        ),
        migrations.AddField(
            model_name='product_master',
            name='units_of_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uom', to='inventory.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='gst_list',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gstdetail', to='inventory.product_master'),
        ),
        migrations.AddField(
            model_name='godown',
            name='parent',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.godown'),
        ),
        migrations.AlterUniqueTogether(
            name='std_rate',
            unique_together={('product', 'rate_type', 'applicable_from')},
        ),
    ]
