# Generated by Django 4.0.6 on 2022-08-30 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='godown',
            options={'ordering': ['godown_type', 'name']},
        ),
        migrations.AlterModelOptions(
            name='product_master',
            options={'ordering': ['product_code']},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='scheme',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subbrand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subclass',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='unitofmeasure',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='uqc',
            options={'ordering': ['name']},
        ),
    ]
