# Generated by Django 4.0.6 on 2022-09-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='godown',
            name='name',
            field=models.CharField(max_length=151, unique=True),
        ),
    ]
