# Generated by Django 4.0.6 on 2022-09-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_godown_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasure',
            name='name',
            field=models.CharField(max_length=151, unique=True),
        ),
    ]
