# Generated by Django 4.0.6 on 2022-09-03 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_unitofmeasure_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='std_rate',
            unique_together={('product', 'rate_type')},
        ),
    ]
