# Generated by Django 4.0.6 on 2022-09-20 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0006_asm_created_asm_updated_currency_created_and_more'),
        ('inventory', '0008_brand_created_brand_updated_category_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='dl_purchase',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='product_type_purchase_ledger', to='ledgers.ledgerstype'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='dl_sales',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='product_type_sales_ledger', to='ledgers.ledgerstype'),
        ),
    ]
