# Generated by Django 4.0.6 on 2022-12-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_producttype_dl_purchase_producttype_dl_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_master',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
