# Generated by Django 4.0.5 on 2023-01-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_gst_list_hsncode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gst_list',
            name='calc_type',
            field=models.CharField(max_length=151),
        ),
        migrations.AlterField(
            model_name='gst_list',
            name='suply_type',
            field=models.CharField(max_length=151),
        ),
        migrations.AlterField(
            model_name='gst_list',
            name='taxability',
            field=models.CharField(max_length=151),
        ),
    ]
