# Generated by Django 4.0.5 on 2022-08-26 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=151)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=151)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=151)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=151, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=151, null=True, unique=True)),
                ('name', models.CharField(max_length=151, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Price_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=151)),
                ('code', models.CharField(blank=True, max_length=151, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=151)),
            ],
        ),
        migrations.CreateModel(
            name='Rsm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=151)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.region')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=151, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zsm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=151)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.zone')),
            ],
            options={
                'unique_together': {('zone', 'name')},
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=151)),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ledgers.country')),
            ],
            options={
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Se',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=151)),
                ('asm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.asm')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.region')),
                ('rsm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.rsm')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.zone')),
                ('zsm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.zsm')),
            ],
            options={
                'unique_together': {('zone', 'region', 'zsm', 'rsm', 'asm', 'name')},
            },
        ),
        migrations.AddField(
            model_name='rsm',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.zone'),
        ),
        migrations.AddField(
            model_name='rsm',
            name='zsm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.zsm'),
        ),
        migrations.AddField(
            model_name='region',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.zone'),
        ),
        migrations.CreateModel(
            name='Party_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=151)),
                ('maintain_bill_by_bill', models.BooleanField(default=True)),
                ('dafault_credit_period', models.CharField(blank=True, max_length=151, null=True)),
                ('check_credit_days', models.BooleanField(default=True)),
                ('credit_limit', models.CharField(blank=True, max_length=151, null=True)),
                ('closing_balance', models.CharField(blank=True, max_length=151, null=True)),
                ('override_credit_limit', models.BooleanField(default=False)),
                ('payment_terms', models.CharField(blank=True, max_length=151, null=True)),
                ('allow_loose_packing', models.BooleanField(default=True)),
                ('istcsapplicable', models.BooleanField(default=False)),
                ('vendor_code', models.CharField(blank=True, max_length=151, null=True, unique=True)),
                ('mailing_name', models.CharField(max_length=151)),
                ('addressline1', models.CharField(blank=True, max_length=151, null=True)),
                ('addressline2', models.CharField(blank=True, max_length=151, null=True)),
                ('addressline3', models.CharField(blank=True, max_length=151, null=True)),
                ('pin_code', models.DecimalField(decimal_places=0, max_digits=6)),
                ('mobile_no', models.DecimalField(decimal_places=0, max_digits=12)),
                ('contact_details', models.BooleanField(default=False)),
                ('contact_person', models.CharField(blank=True, max_length=151, null=True)),
                ('phone_no', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('fax_no', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=250, null=True)),
                ('cc_email', models.EmailField(blank=True, max_length=250, null=True)),
                ('website', models.CharField(blank=True, max_length=151, null=True)),
                ('multiple_address_list', models.BooleanField(default=False)),
                ('gst_registration_type', models.CharField(choices=[('1', 'Composition'), ('2', 'Consumer'), ('0', 'Unknown'), ('3', 'Regular'), ('4', 'Unregistered')], max_length=151)),
                ('gstin', models.CharField(blank=True, max_length=151, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=151, null=True)),
                ('transation_type', models.CharField(blank=True, max_length=151, null=True)),
                ('bank', models.CharField(blank=True, max_length=151, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=151, null=True)),
                ('account_no', models.CharField(blank=True, max_length=151, null=True)),
                ('account_name', models.CharField(blank=True, max_length=151, null=True)),
                ('asm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledgers.asm')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.country')),
                ('devision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.division')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.group')),
                ('party_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.partytype')),
                ('price_level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ledgers.price_level')),
                ('products', models.ManyToManyField(related_name='party', to='inventory.product_master')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledgers.region')),
                ('rsm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledgers.rsm')),
                ('se', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledgers.se')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.state')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledgers.zone')),
                ('zsm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledgers.zsm')),
            ],
            options={
                'unique_together': {('name', 'group')},
            },
        ),
        migrations.CreateModel(
            name='Party_contact_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('address_type', models.CharField(max_length=151)),
                ('mailing_name', models.CharField(max_length=151)),
                ('addressline1', models.CharField(blank=True, max_length=151, null=True)),
                ('addressline2', models.CharField(blank=True, max_length=151, null=True)),
                ('addressline3', models.CharField(blank=True, max_length=151, null=True)),
                ('country', models.CharField(max_length=151)),
                ('state', models.CharField(max_length=151)),
                ('city', models.CharField(max_length=151)),
                ('pin_code', models.DecimalField(decimal_places=0, max_digits=12)),
                ('contact_person', models.CharField(blank=True, max_length=151, null=True)),
                ('phone_no', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('mobile_no', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('fax_no', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=250, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=250, null=True)),
                ('gst_registration_type', models.CharField(choices=[('1', 'Composition'), ('2', 'Consumer'), ('3', 'Regular'), ('4', 'Unregistered')], max_length=151)),
                ('gstin', models.CharField(max_length=151)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.party_master')),
            ],
        ),
        migrations.CreateModel(
            name='LedgersType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=151)),
                ('gst_applicable', models.CharField(choices=[('1', 'Applicable'), ('2', 'Not Applicable'), ('3', 'Undefined')], max_length=151)),
                ('type_of_supply', models.CharField(choices=[('1', 'Goods'), ('2', 'Serives')], max_length=151)),
                ('under', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.group')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ledgers.state'),
        ),
        migrations.AddField(
            model_name='asm',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.region'),
        ),
        migrations.AddField(
            model_name='asm',
            name='rsm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.rsm'),
        ),
        migrations.AddField(
            model_name='asm',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.zone'),
        ),
        migrations.AddField(
            model_name='asm',
            name='zsm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.zsm'),
        ),
        migrations.AlterUniqueTogether(
            name='rsm',
            unique_together={('zone', 'region', 'zsm', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('zone', 'name')},
        ),
        migrations.CreateModel(
            name='Price_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('applicable_from', models.DateField(auto_now=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('price_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.price_level')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pricelist', to='inventory.product_master')),
            ],
            options={
                'ordering': ('applicable_from',),
                'unique_together': {('price_level', 'product')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('state', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='asm',
            unique_together={('zone', 'region', 'zsm', 'rsm', 'name')},
        ),
    ]
