# Generated by Django 4.0.6 on 2022-08-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterModelOptions(
            name='asm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='ledgerstype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='price_level',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='price_list',
            options={'ordering': ('product',)},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='rsm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='se',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='zsm',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=151, unique=True),
        ),
    ]
