# Generated by Django 4.0.6 on 2022-09-02 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0002_currency_alter_asm_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('zone', 'name')},
        ),
    ]
