# Generated by Django 4.0.6 on 2022-10-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0007_alter_party_master_cc_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party_contact_details',
            name='fax_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='party_contact_details',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='party_contact_details',
            name='phone_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
