# Generated by Django 4.0.6 on 2022-10-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0008_alter_party_contact_details_fax_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party_master',
            name='gst_registration_type',
            field=models.CharField(max_length=151),
        ),
    ]
