# Generated by Django 4.0.6 on 2022-10-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0009_alter_party_master_gst_registration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party_contact_details',
            name='pin_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='party_master',
            name='fax_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='party_master',
            name='mobile_no',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='party_master',
            name='phone_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='party_master',
            name='pin_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
