# Generated by Django 4.0.6 on 2022-10-12 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0010_alter_party_contact_details_pin_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party_contact_details',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.city'),
        ),
        migrations.AlterField(
            model_name='party_contact_details',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.country'),
        ),
        migrations.AlterField(
            model_name='party_contact_details',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.state'),
        ),
    ]
