# Generated by Django 4.0.6 on 2022-10-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0011_alter_party_contact_details_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party_contact_details',
            name='gst_registration_type',
            field=models.CharField(max_length=151),
        ),
    ]
