# Generated by Django 4.0.6 on 2022-10-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0012_alter_party_contact_details_gst_registration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party_contact_details',
            name='gst_registration_type',
            field=models.CharField(blank=True, max_length=151, null=True),
        ),
        migrations.AlterField(
            model_name='party_contact_details',
            name='gstin',
            field=models.CharField(blank=True, max_length=151, null=True),
        ),
        migrations.AlterField(
            model_name='party_contact_details',
            name='mailing_name',
            field=models.CharField(blank=True, max_length=151, null=True),
        ),
    ]
