# Generated by Django 4.0.5 on 2022-08-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('tally_name', models.CharField(max_length=51)),
                ('ledger_name', models.CharField(max_length=51)),
                ('color', models.CharField(max_length=25)),
                ('ipaddress', models.CharField(default='http://localhost:9001', max_length=100)),
                ('dis_addtype', models.CharField(max_length=100)),
                ('dis_name', models.CharField(max_length=100)),
                ('dis_add1', models.CharField(max_length=100)),
                ('dis_add2', models.CharField(max_length=100)),
                ('dis_add3', models.CharField(max_length=100)),
                ('dis_country', models.CharField(max_length=100)),
                ('dis_state', models.CharField(max_length=100)),
                ('dis_city', models.CharField(max_length=100)),
                ('dis_pincode', models.CharField(max_length=100)),
                ('dis_gstin', models.CharField(max_length=100)),
                ('pan_no', models.CharField(max_length=10)),
                ('so_series', models.CharField(max_length=10)),
                ('dn_series', models.CharField(max_length=10)),
                ('inv_series', models.CharField(max_length=10)),
                ('debitnote_series', models.CharField(max_length=10)),
                ('sales_qdn_series', models.CharField(max_length=10)),
                ('rso_series', models.CharField(max_length=10)),
                ('po_series', models.CharField(max_length=10)),
                ('ict_series', models.CharField(max_length=10)),
                ('grn_series', models.CharField(max_length=10)),
                ('pi_series', models.CharField(max_length=10)),
                ('creditnote_series', models.CharField(max_length=10)),
                ('purchase_qdn_series', models.CharField(max_length=10)),
                ('purchase_return_series', models.CharField(max_length=10)),
                ('joborder_series', models.CharField(max_length=10, verbose_name='Job Order Series')),
                ('job_series', models.CharField(max_length=10, verbose_name='Job Card Series')),
                ('rm_series', models.CharField(max_length=10, verbose_name='RMIndent Series')),
                ('cms_series', models.CharField(max_length=10, verbose_name='Consumables Series')),
                ('pds_series', models.CharField(max_length=10, verbose_name='Production Series')),
            ],
        ),
    ]
