# Generated by Django 4.0.6 on 2022-09-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_created_company_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='color',
        ),
    ]
