# Generated by Django 4.0.6 on 2022-09-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_company_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pinv_series',
            field=models.CharField(default='PI00001', max_length=10),
            preserve_default=False,
        ),
    ]
