# Generated by Django 4.0.6 on 2022-08-30 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditnote',
            options={'ordering': ['-cn_date']},
        ),
        migrations.AlterModelOptions(
            name='delivery_note',
            options={'ordering': ['-dn_date']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-inv_date']},
        ),
        migrations.AlterModelOptions(
            name='qdn',
            options={'ordering': ['-qdn_date']},
        ),
        migrations.AlterModelOptions(
            name='rso',
            options={'ordering': ['-rso_date']},
        ),
        migrations.AlterModelOptions(
            name='saleqty',
            options={'ordering': ['product']},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-so_date']},
        ),
    ]
