# Generated by Django 4.0.6 on 2022-09-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_creditnote_options_alter_delivery_note_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='channel',
            field=models.CharField(default='NA', max_length=51),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='division',
            field=models.CharField(default='NA', max_length=51),
            preserve_default=False,
        ),
    ]
