# Generated by Django 4.0.6 on 2022-09-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_invoice_channel_invoice_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rso',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='rso',
            name='buyer_address1',
        ),
        migrations.RemoveField(
            model_name='rso',
            name='buyer_address2',
        ),
        migrations.RemoveField(
            model_name='rso',
            name='buyer_address3',
        ),
        migrations.RemoveField(
            model_name='rso',
            name='buyer_address_type',
        ),
        migrations.RemoveField(
            model_name='rso',
            name='buyer_city',
        ),
        migrations.RemoveField(
            model_name='rso',
            name='buyer_country',
        ),
        migrations.RemoveField(
            model_name='rso',
            name='buyer_gst_reg_type',
        ),
        migrations.RemoveField(
            model_name='rso',
            name='buyer_gstin',
        ),
        migrations.RemoveField(
            model_name='rso',
            name='buyer_mailingname',
        ),
        migrations.RemoveField(
            model_name='rso',
            name='buyer_pincode',
        ),
        migrations.RemoveField(
            model_name='rso',
            name='buyer_state',
        ),
        migrations.RemoveField(
            model_name='rso',
            name='ol_rate',
        ),
        migrations.RemoveField(
            model_name='rso',
            name='other',
        ),
        migrations.RemoveField(
            model_name='rso',
            name='other_ledger',
        ),
    ]
