# Generated by Django 4.0.6 on 2022-09-04 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_rso_buyer_remove_rso_buyer_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnoteitems',
            name='creditNote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.creditnote'),
        ),
        migrations.AlterField(
            model_name='dnitems',
            name='dn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.delivery_note'),
        ),
        migrations.AlterField(
            model_name='invitems',
            name='inv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.invoice'),
        ),
        migrations.AlterField(
            model_name='qdnitems',
            name='qdn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.qdn'),
        ),
        migrations.AlterField(
            model_name='rsoitems',
            name='rso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.rso'),
        ),
        migrations.AlterField(
            model_name='soitems',
            name='so',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesorder'),
        ),
    ]
