# Generated by Django 4.0.6 on 2022-09-04 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_currency'),
        ('sales', '0005_alter_creditnoteitems_creditnote_alter_dnitems_dn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingsheet',
            name='dn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.delivery_note'),
        ),
        migrations.AlterField(
            model_name='packingsheet',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product_master'),
        ),
    ]
