# Generated by Django 4.0.6 on 2022-09-04 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0005_alter_division_name'),
        ('sales', '0006_alter_packingsheet_dn_alter_packingsheet_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='rso',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='rso_buyer', to='ledgers.party_master'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rso',
            name='buyer_address1',
            field=models.CharField(default=1, max_length=51),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rso',
            name='buyer_address2',
            field=models.CharField(default=1, max_length=51),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rso',
            name='buyer_address3',
            field=models.CharField(default=1, max_length=51),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rso',
            name='buyer_address_type',
            field=models.CharField(default=1, max_length=51),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rso',
            name='buyer_city',
            field=models.CharField(default=1, max_length=51),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rso',
            name='buyer_country',
            field=models.CharField(default=1, max_length=51),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rso',
            name='buyer_gst_reg_type',
            field=models.CharField(default=1, max_length=51),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rso',
            name='buyer_gstin',
            field=models.CharField(default=1, max_length=51),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rso',
            name='buyer_mailingname',
            field=models.CharField(default=1, max_length=51),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rso',
            name='buyer_pincode',
            field=models.CharField(default=1, max_length=51),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rso',
            name='buyer_state',
            field=models.CharField(default=1, max_length=51),
            preserve_default=False,
        ),
    ]
