# Generated by Django 4.0.6 on 2022-09-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_rso_buyer_rso_buyer_address1_rso_buyer_address2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rso',
            name='is_cm',
            field=models.BooleanField(default=False),
        ),
    ]
