# Generated by Django 4.0.6 on 2022-09-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_rso_is_cm'),
    ]

    operations = [
        migrations.AddField(
            model_name='rso',
            name='rso_ref',
            field=models.CharField(blank=True, max_length=51, null=True),
        ),
    ]
