# Generated by Django 4.0.6 on 2022-09-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_salesorder_created_alter_salesorder_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='shipto_gstin',
            field=models.CharField(blank=True, max_length=51, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shipto_pan_no',
            field=models.CharField(blank=True, max_length=51, null=True),
        ),
    ]
