# Generated by Django 4.0.6 on 2022-09-22 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0006_asm_created_asm_updated_currency_created_and_more'),
        ('sales', '0013_alter_dnitems_available_qty_alter_dnitems_mrp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.DecimalField(decimal_places=2, max_digits=20)),
                ('months', models.DateField()),
                ('asm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.asm')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.party_master')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.region')),
                ('rsm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.rsm')),
                ('se', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.se')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.zone')),
                ('zsm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.zsm')),
            ],
        ),
    ]
