# Generated by Django 4.0.6 on 2022-09-23 05:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone



class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_company_color'),
        ('sales', '0014_salestarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestarget',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salestarget',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salestarget',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
