# Generated by Django 4.0.6 on 2022-09-29 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_proformainvoice_proformainvitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salestarget',
            old_name='customer',
            new_name='buyer',
        ),
        migrations.RemoveField(
            model_name='salestarget',
            name='company',
        ),
    ]
