# Generated by Django 4.0.6 on 2022-10-01 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_rename_customer_salestarget_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformainvitems',
            name='inv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.proformainvoice'),
        ),
    ]
