# Generated by Django 4.0.6 on 2022-10-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_rename_destination_proformainvoice_destintaion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_note',
            name='buyer_address1',
            field=models.CharField(blank=True, max_length=151, null=True),
        ),
        migrations.AlterField(
            model_name='delivery_note',
            name='buyer_address2',
            field=models.CharField(blank=True, max_length=151, null=True),
        ),
        migrations.AlterField(
            model_name='delivery_note',
            name='buyer_address3',
            field=models.CharField(blank=True, max_length=151, null=True),
        ),
        migrations.AlterField(
            model_name='delivery_note',
            name='buyer_mailingname',
            field=models.CharField(max_length=151),
        ),
        migrations.AlterField(
            model_name='delivery_note',
            name='shipto_address1',
            field=models.CharField(blank=True, max_length=151, null=True),
        ),
        migrations.AlterField(
            model_name='delivery_note',
            name='shipto_address2',
            field=models.CharField(blank=True, max_length=151, null=True),
        ),
        migrations.AlterField(
            model_name='delivery_note',
            name='shipto_address3',
            field=models.CharField(blank=True, max_length=151, null=True),
        ),
        migrations.AlterField(
            model_name='delivery_note',
            name='shipto_mailingname',
            field=models.CharField(max_length=151),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='buyer_address1',
            field=models.CharField(max_length=151),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='buyer_address2',
            field=models.CharField(max_length=151),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='buyer_address3',
            field=models.CharField(max_length=151),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='buyer_mailingname',
            field=models.CharField(max_length=151),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shipto_address1',
            field=models.CharField(max_length=151),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shipto_address2',
            field=models.CharField(max_length=151),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shipto_address3',
            field=models.CharField(max_length=151),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shipto_mailingname',
            field=models.CharField(max_length=151),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='buyer_address1',
            field=models.CharField(max_length=151),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='buyer_address2',
            field=models.CharField(max_length=151),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='buyer_address3',
            field=models.CharField(max_length=151),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='buyer_mailingname',
            field=models.CharField(max_length=151),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='shipto_address1',
            field=models.CharField(max_length=151),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='shipto_address2',
            field=models.CharField(max_length=151),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='shipto_address3',
            field=models.CharField(max_length=151),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='shipto_mailingname',
            field=models.CharField(max_length=151),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='buyer_address1',
            field=models.CharField(blank=True, max_length=151, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='buyer_address2',
            field=models.CharField(blank=True, max_length=151, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='buyer_address3',
            field=models.CharField(blank=True, max_length=151, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='buyer_mailingname',
            field=models.CharField(max_length=151),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='shipto_address1',
            field=models.CharField(blank=True, max_length=151, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='shipto_address2',
            field=models.CharField(blank=True, max_length=151, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='shipto_address3',
            field=models.CharField(blank=True, max_length=151, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='shipto_mailingname',
            field=models.CharField(max_length=151),
        ),
    ]
