# Generated by Django 4.0.6 on 2022-10-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_alter_delivery_note_buyer_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_note',
            name='shipto_pan_no',
            field=models.CharField(blank=True, max_length=51, null=True),
        ),
    ]
