# Generated by Django 4.0.6 on 2022-10-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_alter_delivery_note_shipto_pan_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='shipto_pan_no',
            field=models.CharField(blank=True, max_length=51, null=True),
        ),
    ]
