# Generated by Django 4.0.6 on 2022-10-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_alter_salesorder_ref_no_alter_salesorder_so_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Cancelled'), ('3', 'Sent to tally'), ('4', 'Mailed')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Cancelled'), ('3', 'Inovice'), ('4', 'Mailed')], default=1, max_length=20),
        ),
    ]
