# Generated by Django 4.0.6 on 2022-11-07 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_alter_invoice_status_alter_proformainvoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rso',
            name='ref_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
