# Generated by Django 4.0.6 on 2022-11-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_rso_ref_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rso',
            name='ref_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
