# Generated by Django 4.0.6 on 2022-11-11 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_alter_rso_ref_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingsheet',
            name='total_box',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rso',
            name='inv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.invoice'),
        ),
    ]
