# Generated by Django 4.0.6 on 2022-11-21 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_alter_packingsheet_total_box_alter_rso_inv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitems',
            old_name='new_qty',
            new_name='nb_qty',
        ),
    ]
