# Generated by Django 4.0.6 on 2022-11-21 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0029_invitems_nf_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proformainvitems',
            old_name='new_qty',
            new_name='nb_qty',
        ),
    ]
