# Generated by Django 4.0.6 on 2022-11-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_rename_qdn_qty_qdn_qb_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='qdn',
            name='qf_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
