# Generated by Django 4.0.6 on 2022-11-21 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_qdn_qf_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qdnitems',
            old_name='qdn_qty',
            new_name='qb_qty',
        ),
        migrations.RenameField(
            model_name='rso',
            old_name='rso_qty',
            new_name='rb_qty',
        ),
        migrations.RenameField(
            model_name='rsoitems',
            old_name='rso_qty',
            new_name='rb_qty',
        ),
    ]
