# Generated by Django 4.0.6 on 2022-11-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0034_rename_qdn_qty_qdnitems_qb_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qdnitems',
            name='qf_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rso',
            name='rf_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsoitems',
            name='rf_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
