# Generated by Django 4.0.6 on 2022-11-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0035_qdnitems_qf_qty_rso_rf_qty_rsoitems_rf_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rso',
            name='buyer_gst_reg_type',
            field=models.CharField(blank=True, max_length=51, null=True),
        ),
        migrations.AlterField(
            model_name='rso',
            name='buyer_gstin',
            field=models.CharField(blank=True, max_length=51, null=True),
        ),
    ]
