# Generated by Django 4.0.5 on 2022-12-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0036_alter_rso_buyer_gst_reg_type_alter_rso_buyer_gstin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='carrier_agent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='carrier_agent_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='mode_of_payment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='other_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='terms_of_delivery',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
