# Generated by Django 4.0.6 on 2022-12-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0038_alter_invoice_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='mrpvalue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='omrpvalue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='qdn',
            name='mrpvalue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='qdn',
            name='omrpvalue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='rso',
            name='mrpvalue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='rso',
            name='omrpvalue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
