# Generated by Django 4.0.5 on 2022-12-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0039_creditnote_mrpvalue_creditnote_omrpvalue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rso',
            name='buyer_address1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rso',
            name='buyer_address2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rso',
            name='buyer_address3',
            field=models.CharField(max_length=100),
        ),
    ]
