# Generated by Django 4.0.6 on 2022-12-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0040_alter_rso_buyer_address1_alter_rso_buyer_address2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnoteitems',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qdnitems',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsoitems',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
