# Generated by Django 4.0.6 on 2022-12-20 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0014_party_master_is_transporter'),
        ('sales', '0041_creditnoteitems_mrp_qdnitems_mrp_rsoitems_mrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='buyer',
            field=models.ForeignKey(default=200, on_delete=django.db.models.deletion.PROTECT, related_name='cn_buyer', to='ledgers.party_master'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditnote',
            name='buyer_address1',
            field=models.CharField(default=1, max_length=151),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditnote',
            name='buyer_address2',
            field=models.CharField(default=1, max_length=151),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditnote',
            name='buyer_address3',
            field=models.CharField(default=1, max_length=151),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditnote',
            name='buyer_address_type',
            field=models.CharField(default=1, max_length=51),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditnote',
            name='buyer_city',
            field=models.CharField(default=1, max_length=51),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditnote',
            name='buyer_country',
            field=models.CharField(default=1, max_length=51),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditnote',
            name='buyer_gst_reg_type',
            field=models.CharField(default=1, max_length=51),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditnote',
            name='buyer_gstin',
            field=models.CharField(blank=True, max_length=51, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='buyer_mailingname',
            field=models.CharField(default=1, max_length=151),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditnote',
            name='buyer_pincode',
            field=models.CharField(default=1, max_length=51),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditnote',
            name='buyer_state',
            field=models.CharField(default=1, max_length=51),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditnote',
            name='channel',
            field=models.CharField(default=1, max_length=51),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditnote',
            name='division',
            field=models.CharField(default=1, max_length=51),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='dn',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inv', to='sales.delivery_note'),
        ),
    ]
