# Generated by Django 4.0.6 on 2022-12-20 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0046_rename_rate_diff_creditnoteitems_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditnoteitems',
            old_name='creditNote',
            new_name='inv',
        ),
    ]
