# Generated by Django 4.0.6 on 2022-12-20 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0047_rename_creditnote_creditnoteitems_inv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qdn',
            old_name='qb_qty',
            new_name='bill_qty',
        ),
        migrations.RenameField(
            model_name='qdn',
            old_name='qf_qty',
            new_name='free_qty',
        ),
        migrations.RenameField(
            model_name='qdnitems',
            old_name='billed_qty',
            new_name='billed',
        ),
    ]
