# Generated by Django 4.0.6 on 2022-12-20 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0048_rename_qb_qty_qdn_bill_qty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qdnitems',
            old_name='qb_qty',
            new_name='billed_qty',
        ),
        migrations.RenameField(
            model_name='qdnitems',
            old_name='qf_qty',
            new_name='free_qty',
        ),
        migrations.RenameField(
            model_name='qdnitems',
            old_name='qdn',
            new_name='inv',
        ),
    ]
