# Generated by Django 4.0.6 on 2022-12-20 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0049_rename_qb_qty_qdnitems_billed_qty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsoitems',
            old_name='billed_qty',
            new_name='billed',
        ),
        migrations.RenameField(
            model_name='rsoitems',
            old_name='rso',
            new_name='inv',
        ),
    ]
