# Generated by Django 4.0.6 on 2022-12-20 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0050_rename_billed_qty_rsoitems_billed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsoitems',
            old_name='rb_qty',
            new_name='billed_qty',
        ),
        migrations.RenameField(
            model_name='rsoitems',
            old_name='rf_qty',
            new_name='free_qty',
        ),
    ]
