# Generated by Django 4.0.5 on 2022-12-27 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0052_rename_rb_qty_rso_bill_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rso',
            name='rso_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
