# Generated by Django 4.0.5 on 2022-12-28 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0054_packingsheet_remarks_alter_packingsheet_mrp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_note',
            name='dn_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='so_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
