# Generated by Django 4.0.5 on 2023-01-03 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_pinv_series'),
        ('sales', '0055_alter_delivery_note_dn_date_alter_salesorder_so_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salesorder',
            unique_together={('company', 'so_no')},
        ),
    ]
