# Generated by Django 4.0.5 on 2023-01-05 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0056_alter_salesorder_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['so_no']},
        ),
    ]
