# Generated by Django 4.0.5 on 2023-01-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0057_alter_salesorder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Cancelled'), ('3', 'Sent to tally'), ('4', 'Mailed')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='qdn',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Cancelled'), ('3', 'Sent to tally'), ('4', 'Mailed')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='rso',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Cancelled'), ('3', 'Sent to tally'), ('4', 'Mailed')], default=1, max_length=20),
        ),
    ]
